kind = "mobile"
previewPath = "/"
title = "KAYGO Mobile"
version = "1.0.0"
id = "artifacts/kaygo-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23137

[services.development]
run = "pnpm --filter @workspace/kaygo-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kaygo-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/kaygo-mobile", "run", "serve" ]

[services.env]
PORT = "23137"
BASE_PATH = "/"
